# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
#"--provide=virtualbox" 

# Update count to have multiple instances for node only
# `prefix` => [count, ip_start]
nodes = {
   'KernelDevBox'      => [1, 2],
}

Vagrant.configure("2") do |config|

  # Defaults
  config.vm.box = "centos/7"
  config.vm.usable_port_range= 4000..4200
  #ToDo :  Update path to your source code structure.
  #config.vm.synced_folder "~/repos/GoWork/src", "/gowork/src", type: "nfs"

  # Refer back to node definition, we are iterating thru nodes definition
  nodes.each do |prefix, (count,ip_start)|
    count.times do |i|
        hostname = "%s%d" % [prefix, (i+1)]

      config.vm.define "#{hostname}" do |box|
        box.vm.hostname = "#{hostname}"
        box.vm.network :private_network, ip: "192.168.7.#{ip_start+i}", :netmask => "255.255.255.0"
        box.vm.provision :shell, :path => "#{prefix}.sh"

        # Otherwise using VirtualBox
        box.vm.provider :virtualbox do |vbox|
        # Defaults
        vbox.customize ["modifyvm", :id, "--memory", 2048]
        vbox.customize ["modifyvm", :id, "--cpus", 2]
        end
    end
    end
  end
end
